services:
  - type: web
    name: gold-scraper
    env: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: 0
