services:
  - type: web
    name: gold-scraper
    env: node
    plan: free

    buildCommand: npm install
    startCommand: node server.js

    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright
      - key: NODE_VERSION
        value: 20
